# Generated by Django 4.1.5 on 2023-01-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_phone_number',
            field=models.CharField(default='', max_length=25, verbose_name='Телефон домашний'),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Женат/Замужем'), ('divorced', 'Разведен/Разведена'), ('widowed', 'Вдовец/Вдова'), ('not_married', 'Не женат/Не замужем')], max_length=250, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_phone_number',
            field=models.CharField(default='', max_length=25, verbose_name='Телефон мобильный'),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_occupation',
            field=models.CharField(default='', max_length=250, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_place',
            field=models.CharField(default='', max_length=250, verbose_name='Место работы'),
        ),
    ]
