# Generated by Django 4.1.5 on 2023-01-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_email_alter_client_home_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_phone_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон домашний'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_phone_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон мобильный'),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_occupation',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_place',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Место работы'),
        ),
    ]
