# Generated by Django 4.1.5 on 2023-01-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_email_alter_client_home_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
    ]
