# Generated by Django 4.1.5 on 2023-01-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_client_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Идентификационный номер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('first_name', 'surname', 'father_name', 'birth_at', 'passport_series', 'passport_number', 'passport_issuer', 'passport_issue_at', 'id_number', 'birth_city', 'current_city', 'current_live_address', 'home_phone_number', 'mobile_phone_number', 'email', 'work_place', 'work_occupation', 'city_of_residence', 'marital_status', 'citizenship', 'is_disabled', 'is_retired', 'monthly_income')},
        ),
    ]
