# Generated by Django 4.1.5 on 2023-01-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_client_id_number_alter_client_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('first_name', 'surname', 'father_name')},
        ),
    ]
